### PR TITLE
Add `omit divergences` argument for segments within `drb-segs-spatial`

### LINKED ISSUE #13: Omit divergences from crosswalk table for reaches within `drb_segs_spatial`
Even if `omit_divergences = TRUE`, some reaches in `p2_drb_comids_all_tribs` represent divergent reaches (where `STREAMORDE != STREAMCALC`). It appears that these reaches are associated with PRMS/NHM segments included in `drb_segs_spatial.` Add a step to `get_intersecting_nhdplus_catchments()` to exclude these reaches when building the crosswalk table if `omit_divergences = TRUE`.

```
> tar_load(p1_nhdv2reaches_sf)
> tar_load(p2_drb_comids_all_tribs)
> p2_drb_comids_all_tribs %>% 
+     mutate(COMID = as.integer(COMID)) %>% 
+     left_join(sf::st_drop_geometry(p1_nhdv2reaches_sf[,c("COMID","STREAMORDE","STREAMCALC")]), by = "COMID") %>% 
+     filter(STREAMORDE != STREAMCALC) %>% pull(PRMS_segid) %>% 
+     unique()
 [1] "1256_1" "2137_1" "2138_1" "233_1"  "249_1"  "2757_1" "2758_1" "2765_1" "2766_1" "2767_1" "2797_1" "354_1"  "355_1"  "396_1"  "593_1" 
>
```

### PR DESCRIPTION
**Pull request by lekoenig**
This PR adds an argument, `omit_divergences` to the functions `pair_nhd_catchments` and `get_intersecting_nhdplus_catchments` so that if TRUE, divergent reaches will be omitted when building the crosswalk table for NHM/PRMS segments defined in `drb_segs_spatial` (see #13). 

I built the pipeline after making these changes and checked that the `comid_cat`'s no longer contain divergent reaches:
```
> tar_load(p1_nhdv2reaches_sf)
> tar_load(p2_drb_comids_all_tribs)
> p2_drb_comids_all_tribs %>% 
+     mutate(COMID = as.integer(COMID)) %>% 
+     left_join(sf::st_drop_geometry(p1_nhdv2reaches_sf[,c("COMID","STREAMORDE","STREAMCALC")]), by = "COMID") %>% 
+     # subset any divergent COMIDs (where stream order != stream calc):
+     filter(STREAMORDE != STREAMCALC) %>% 
+     pull(PRMS_segid) %>% 
+     unique()
character(0)
>
```

### CODE REVIEW

**Review by jds485 — APPROVED** [review]
This looks good to me. I built the pipeline with a newer sf version: 1.0.6. git shows a difference in the resulting file, but it might just be line endings (see below - did you run this pipeline on Linux or Windows?). Let me know if you'd like to take a look at the resulting xwalk.csv file.

        modified:   2_process/out/GFv1_NHDv2_xwalk.csv
        modified:   2_process/out/GFv1_catchments_edited.gpkg

> git diff 2_process/out/GFv1_NHDv2_xwalk.csv
warning: LF will be replaced by CRLF in 2_process/out/GFv1_NHDv2_xwalk.csv.
The file will have its original line endings in your working directory

**Comment by lekoenig** [comment]
> git shows a difference in the resulting file

So there _should_ be a change in the resulting crosswalk file based on the changes in this PR. This was a goof on my part. I forgot to account for how we were accessing flowlines in the special handling cases, and so divergent reaches were essentially "leaking through" to the crosswalk table for reaches within `drb_segs_spatial` even when `omit_divergences` was set to TRUE. Let me know if you think this still might be related to `sf` versions, though. 

Thanks for your review, @jds485!

**Comment by jds485** [comment]
Just to clarify, I (git) sees a difference between the version of `2_process/out/GFv1_NHDv2_xwalk.csv` that was in the repo before I ran the code and the version that was built after I ran the code. So I think any difference in these files would be caused by OS, R version, or sf version differences

**Comment by lekoenig** [comment]
Ah, OK so a difference relative to the version committed in this PR? Feel free to send me the output file and I can double check the contents.

**Comment by lekoenig** [comment]
Thanks for sending the crosswalk file. It's odd to me that git is showing differences. I checked that all the values for `comid_down`, `comid_seg`, and `comid_cat` were the same between the committed file and your version and didn't find any differences. Here's a summary, too:

```
> xwalk <- read_csv("2_process/out/GFv1_NHDv2_xwalk.csv", show_col_types =  FALSE)
> xwalk_jds <- read_csv("2_process/out/GFv1_NHDv2_xwalk_jds.csv", show_col_types =  FALSE)                                                                                                  
>                                                                                                                                                                                           
> all.equal(xwalk_jds, xwalk)
[1] TRUE
> setdiff(xwalk, xwalk_jds)
# A tibble: 0 x 5
# ... with 5 variables: PRMS_segid <chr>, segidnat <dbl>, comid_down <dbl>, comid_seg <chr>, comid_cat <chr>
> 
```

**Comment by jds485** [comment]
Thanks for checking that. git says the difference is in line endings, which would not cause any issues using the data. I think it's good to merge!

**Pull request merged**
